import 'package:flutter/material.dart';
import '../../features/auth/domain/user_model.dart';
import '../../features/auth/domain/workspace_model.dart';
import '../../features/categories/domain/category_model.dart';
import '../../features/categories/domain/tag_model.dart';
import '../../features/tasks/domain/task_model.dart';
import '../../features/calendar/domain/calendar_model.dart';
import '../../features/calendar/domain/calendar_event_model.dart';
import '../../features/reminders/domain/reminder_model.dart';
import '../../features/notes/domain/editor_block_model.dart';
import '../../features/notes/domain/note_page_model.dart';
import '../../features/projects/domain/project_model.dart';

/// Pre-seeded realistic demo data for FlowSpace
class SampleData {
  static final DateTime now = DateTime.now();
  static final DateTime today = DateTime(now.year, now.month, now.day);

  static final User currentUser = User(
    id: 'user-kibret-01',
    email: 'kibret@flowspace.app',
    displayName: 'Kibret',
    avatarUrl: null,
    isGuest: false,
    createdAt: now.subtract(const Duration(days: 30)),
    updatedAt: now,
  );

  static final Workspace defaultWorkspace = Workspace(
    id: 'ws-personal-01',
    name: 'Kibret\'s Workspace',
    icon: '✨',
    ownerId: currentUser.id,
    memberIds: [currentUser.id],
    createdAt: now.subtract(const Duration(days: 30)),
    updatedAt: now,
  );

  static final List<Category> categories = [
    Category(
      id: 'cat-work',
      name: 'Work',
      colorValue: const Color(0xFF6366F1).toARGB32(),
      iconCode: 'work',
      createdAt: now.subtract(const Duration(days: 20)),
      updatedAt: now,
    ),
    Category(
      id: 'cat-research',
      name: 'Research',
      colorValue: const Color(0xFF8B5CF6).toARGB32(),
      iconCode: 'biotech',
      createdAt: now.subtract(const Duration(days: 20)),
      updatedAt: now,
    ),
    Category(
      id: 'cat-study',
      name: 'Study',
      colorValue: const Color(0xFF10B981).toARGB32(),
      iconCode: 'school',
      createdAt: now.subtract(const Duration(days: 20)),
      updatedAt: now,
    ),
    Category(
      id: 'cat-personal',
      name: 'Personal',
      colorValue: const Color(0xFFF59E0B).toARGB32(),
      iconCode: 'person',
      createdAt: now.subtract(const Duration(days: 20)),
      updatedAt: now,
    ),
    Category(
      id: 'cat-finance',
      name: 'Finance',
      colorValue: const Color(0xFF14B8A6).toARGB32(),
      iconCode: 'account_balance',
      createdAt: now.subtract(const Duration(days: 20)),
      updatedAt: now,
    ),
    Category(
      id: 'cat-health',
      name: 'Health',
      colorValue: const Color(0xFFEF4444).toARGB32(),
      iconCode: 'favorite',
      createdAt: now.subtract(const Duration(days: 20)),
      updatedAt: now,
    ),
  ];

  static final List<Tag> tags = [
    Tag(
      id: 'tag-deep-learning',
      name: 'Deep Learning',
      colorValue: const Color(0xFF8B5CF6).toARGB32(),
      createdAt: now,
      updatedAt: now,
    ),
    Tag(
      id: 'tag-urgent',
      name: 'Urgent',
      colorValue: const Color(0xFFEF4444).toARGB32(),
      createdAt: now,
      updatedAt: now,
    ),
    Tag(
      id: 'tag-writing',
      name: 'Writing',
      colorValue: const Color(0xFF3B82F6).toARGB32(),
      createdAt: now,
      updatedAt: now,
    ),
    Tag(
      id: 'tag-review',
      name: 'Review',
      colorValue: const Color(0xFF10B981).toARGB32(),
      createdAt: now,
      updatedAt: now,
    ),
  ];

  static final List<Project> projects = [
    Project(
      id: 'proj-med-ai',
      name: 'Medical AI Research',
      description: 'Contrastive multimodal learning for clinical diagnostics and imaging.',
      icon: '🔬',
      colorValue: const Color(0xFF8B5CF6).toARGB32(),
      status: ProjectStatus.active,
      startDate: today.subtract(const Duration(days: 14)),
      dueDate: today.add(const Duration(days: 45)),
      taskIds: ['task-01', 'task-02', 'task-05'],
      notePageIds: ['page-research-notes', 'page-ai-literature'],
      eventIds: ['event-research-sync'],
      createdAt: now.subtract(const Duration(days: 14)),
      updatedAt: now,
    ),
    Project(
      id: 'proj-flowspace',
      name: 'Productivity App',
      description: 'Cross-platform mobile workspace combining Notion, Calendar, and Todoist.',
      icon: '⚡',
      colorValue: const Color(0xFF6366F1).toARGB32(),
      status: ProjectStatus.active,
      startDate: today.subtract(const Duration(days: 7)),
      dueDate: today.add(const Duration(days: 30)),
      taskIds: ['task-03'],
      notePageIds: ['page-arch-doc'],
      eventIds: ['event-planning'],
      createdAt: now.subtract(const Duration(days: 7)),
      updatedAt: now,
    ),
    Project(
      id: 'proj-personal-site',
      name: 'Personal Website',
      description: 'Interactive portfolio highlighting publications and open source systems.',
      icon: '🌐',
      colorValue: const Color(0xFF10B981).toARGB32(),
      status: ProjectStatus.planning,
      startDate: today,
      dueDate: today.add(const Duration(days: 60)),
      taskIds: ['task-04'],
      notePageIds: [],
      eventIds: [],
      createdAt: now.subtract(const Duration(days: 3)),
      updatedAt: now,
    ),
  ];

  static final List<Task> tasks = [
    Task(
      id: 'task-01',
      title: 'Complete AI research paper draft',
      description: 'Finalize methodology, benchmark results against ViT baseline, and write conclusion.',
      dueDate: today,
      dueTime: '18:00',
      priority: TaskPriority.urgent,
      status: TaskStatus.inProgress,
      projectId: 'proj-med-ai',
      categoryId: 'cat-research',
      tags: ['Deep Learning', 'Writing'],
      estimatedDurationMinutes: 120,
      isCompleted: false,
      subtasks: [
        'Validate AUC score on validation split',
        'Refine ablation study table',
        'Proofread discussion section',
      ],
      subtasksCompleted: [true, true, false],
      createdAt: now.subtract(const Duration(days: 2)),
      updatedAt: now,
    ),
    Task(
      id: 'task-02',
      title: 'Review project documentation',
      description: 'Audit API specifications, verify OpenAPI schemas, and document endpoints.',
      dueDate: today,
      dueTime: '15:30',
      priority: TaskPriority.high,
      status: TaskStatus.todo,
      projectId: 'proj-med-ai',
      categoryId: 'cat-work',
      tags: ['Review'],
      estimatedDurationMinutes: 45,
      isCompleted: false,
      subtasks: [
        'Check authentication flow docs',
        'Verify database schema migration scripts',
      ],
      subtasksCompleted: [false, false],
      createdAt: now.subtract(const Duration(days: 1)),
      updatedAt: now,
    ),
    Task(
      id: 'task-03',
      title: 'Implement Notion-style block editor',
      description: 'Support slash commands, drag-and-drop reordering, and markdown shortcuts.',
      dueDate: today.add(const Duration(days: 1)),
      dueTime: '12:00',
      priority: TaskPriority.high,
      status: TaskStatus.inProgress,
      projectId: 'proj-flowspace',
      categoryId: 'cat-work',
      tags: ['Urgent'],
      estimatedDurationMinutes: 90,
      isCompleted: false,
      subtasks: ['Slash command menu', 'Markdown parser', 'Autosave hook'],
      subtasksCompleted: [true, false, false],
      createdAt: now.subtract(const Duration(days: 3)),
      updatedAt: now,
    ),
    Task(
      id: 'task-04',
      title: 'Prepare university application materials',
      description: 'Update CV, write personal statement, and gather recommendation letters.',
      dueDate: today.add(const Duration(days: 3)),
      dueTime: '17:00',
      priority: TaskPriority.medium,
      status: TaskStatus.todo,
      projectId: null,
      categoryId: 'cat-study',
      tags: ['Writing'],
      estimatedDurationMinutes: 60,
      isCompleted: false,
      subtasks: ['Statement of Purpose', 'Transcripts review'],
      subtasksCompleted: [false, false],
      createdAt: now.subtract(const Duration(days: 4)),
      updatedAt: now,
    ),
    Task(
      id: 'task-05',
      title: 'Set up cross-platform offline database',
      description: 'Create repository interfaces and SQLite / local fallback persistence.',
      dueDate: today.subtract(const Duration(days: 1)),
      dueTime: '11:00',
      priority: TaskPriority.medium,
      status: TaskStatus.completed,
      projectId: 'proj-flowspace',
      categoryId: 'cat-work',
      tags: [],
      estimatedDurationMinutes: 40,
      isCompleted: true,
      completedAt: today.subtract(const Duration(days: 1)),
      subtasks: ['Schema creation', 'Unit tests'],
      subtasksCompleted: [true, true],
      createdAt: now.subtract(const Duration(days: 5)),
      updatedAt: now,
    ),
  ];

  static final List<Calendar> calendars = [
    Calendar(
      id: 'cal-work',
      name: 'Work & Research',
      colorValue: const Color(0xFF6366F1).toARGB32(),
      isVisible: true,
      createdAt: now,
      updatedAt: now,
    ),
    Calendar(
      id: 'cal-personal',
      name: 'Personal & Life',
      colorValue: const Color(0xFF10B981).toARGB32(),
      isVisible: true,
      createdAt: now,
      updatedAt: now,
    ),
  ];

  static final List<CalendarEvent> calendarEvents = [
    CalendarEvent(
      id: 'event-research-sync',
      title: 'Research Meeting: Multimodal AI',
      description: 'Weekly team sync on model convergence, loss curves, and submission target.',
      startDateTime: DateTime(today.year, today.month, today.day, 10, 0),
      endDateTime: DateTime(today.year, today.month, today.day, 11, 30),
      location: 'Conference Room B / Google Meet',
      colorValue: const Color(0xFF8B5CF6).toARGB32(),
      calendarId: 'cal-work',
      participants: ['Dr. Davis', 'Elena Rostova', 'Kibret'],
      reminderMinutesBefore: '15',
      recurrence: 'weekly',
      projectId: 'proj-med-ai',
      createdAt: now.subtract(const Duration(days: 7)),
      updatedAt: now,
    ),
    CalendarEvent(
      id: 'event-planning',
      title: 'Project Planning & Architecture Review',
      description: 'Review Clean Architecture boundaries, offline sync contracts, and UI tokens.',
      startDateTime: DateTime(today.year, today.month, today.day, 14, 0),
      endDateTime: DateTime(today.year, today.month, today.day, 15, 0),
      location: 'Virtual',
      colorValue: const Color(0xFF6366F1).toARGB32(),
      calendarId: 'cal-work',
      participants: ['Kibret'],
      reminderMinutesBefore: '10',
      recurrence: 'none',
      projectId: 'proj-flowspace',
      createdAt: now.subtract(const Duration(days: 2)),
      updatedAt: now,
    ),
    CalendarEvent(
      id: 'event-study',
      title: 'Study Session: Distributed Systems',
      description: 'Deep dive into Raft consensus algorithms and vector clocks.',
      startDateTime: DateTime(today.year, today.month, today.day, 16, 30),
      endDateTime: DateTime(today.year, today.month, today.day, 17, 45),
      location: 'Library',
      colorValue: const Color(0xFF10B981).toARGB32(),
      calendarId: 'cal-personal',
      participants: ['Kibret'],
      reminderMinutesBefore: '15',
      recurrence: 'none',
      projectId: null,
      createdAt: now.subtract(const Duration(days: 1)),
      updatedAt: now,
    ),
    CalendarEvent(
      id: 'event-tomorrow',
      title: 'Sprint Retrospective',
      description: 'Review completed epics and plan upcoming development milestones.',
      startDateTime: DateTime(today.year, today.month, today.day + 1, 11, 0),
      endDateTime: DateTime(today.year, today.month, today.day + 1, 12, 0),
      location: 'Discord Huddle',
      colorValue: const Color(0xFF3B82F6).toARGB32(),
      calendarId: 'cal-work',
      participants: ['Team'],
      reminderMinutesBefore: '15',
      recurrence: 'none',
      projectId: 'proj-flowspace',
      createdAt: now,
      updatedAt: now,
    ),
  ];

  static final List<Reminder> reminders = [
    Reminder(
      id: 'rem-01',
      title: 'Submit journal manuscript revision',
      description: 'Include response letter addressing reviewer #2 comments.',
      scheduledAt: DateTime(today.year, today.month, today.day, 17, 30),
      targetType: ReminderTargetType.task,
      targetId: 'task-01',
      recurrence: ReminderRecurrence.none,
      isCompleted: false,
      createdAt: now.subtract(const Duration(days: 1)),
      updatedAt: now,
    ),
    Reminder(
      id: 'rem-02',
      title: 'Evening stretch & meditation',
      description: 'Disconnect from screens for 20 minutes.',
      scheduledAt: DateTime(today.year, today.month, today.day, 21, 0),
      targetType: ReminderTargetType.standalone,
      targetId: null,
      recurrence: ReminderRecurrence.daily,
      isCompleted: false,
      createdAt: now.subtract(const Duration(days: 3)),
      updatedAt: now,
    ),
  ];

  static final List<NotePage> notePages = [
    NotePage(
      id: 'page-research-notes',
      title: 'AI Project: Research & Literature Review',
      icon: '🧠',
      isFavorite: true,
      projectId: 'proj-med-ai',
      tags: ['Deep Learning', 'Research'],
      blocks: [
        EditorBlock(
          id: 'b-01',
          type: BlockType.callout,
          content: 'Key hypothesis: Cross-attention between medical imaging tensors and unstructured clinical notes significantly improves diagnostic precision.',
          calloutIcon: '💡',
          createdAt: now,
          updatedAt: now,
        ),
        EditorBlock(
          id: 'b-02',
          type: BlockType.heading1,
          content: '1. Theoretical Framework',
          createdAt: now,
          updatedAt: now,
        ),
        EditorBlock(
          id: 'b-03',
          type: BlockType.text,
          content: 'Modern clinical models often suffer from misalignment between pixel space and semantic diagnostic vocabularies. We explore contrastive pretraining with infoNCE loss.',
          createdAt: now,
          updatedAt: now,
        ),
        EditorBlock(
          id: 'b-04',
          type: BlockType.heading2,
          content: '2. Experimental Benchmarks',
          createdAt: now,
          updatedAt: now,
        ),
        EditorBlock(
          id: 'b-05',
          type: BlockType.checklist,
          content: 'Train baseline ResNet-50 on CheXpert dataset',
          isChecked: true,
          createdAt: now,
          updatedAt: now,
        ),
        EditorBlock(
          id: 'b-06',
          type: BlockType.checklist,
          content: 'Evaluate Vision Transformer (ViT-B/16) attention maps',
          isChecked: true,
          createdAt: now,
          updatedAt: now,
        ),
        EditorBlock(
          id: 'b-07',
          type: BlockType.checklist,
          content: 'Perform t-SNE projection of latent embeddings',
          isChecked: false,
          createdAt: now,
          updatedAt: now,
        ),
        EditorBlock(
          id: 'b-08',
          type: BlockType.code,
          content: 'def info_nce_loss(query, positive_key, negative_keys, temp=0.07):\n    logits = torch.matmul(query, positive_key.T) / temp\n    return -torch.log(torch.exp(logits) / sum_exp)',
          codeLanguage: 'python',
          createdAt: now,
          updatedAt: now,
        ),
        EditorBlock(
          id: 'b-09',
          type: BlockType.quote,
          content: '"Simplicity is prerequisite for reliability." — Edsger W. Dijkstra',
          createdAt: now,
          updatedAt: now,
        ),
      ],
      createdAt: now.subtract(const Duration(days: 10)),
      updatedAt: now,
    ),
    NotePage(
      id: 'page-arch-doc',
      title: 'FlowSpace Architecture & Data Flow',
      icon: '🏗️',
      isFavorite: true,
      projectId: 'proj-flowspace',
      tags: ['Writing'],
      blocks: [
        EditorBlock(
          id: 'b-10',
          type: BlockType.callout,
          content: 'FlowSpace follows Clean Architecture with Feature-First modularization and 100% offline-first capability.',
          calloutIcon: '⚡',
          createdAt: now,
          updatedAt: now,
        ),
        EditorBlock(
          id: 'b-11',
          type: BlockType.heading1,
          content: 'Core Architectural Layers',
          createdAt: now,
          updatedAt: now,
        ),
        EditorBlock(
          id: 'b-12',
          type: BlockType.bulletList,
          content: 'Presentation: Riverpod Notifiers + Responsive Widgets',
          createdAt: now,
          updatedAt: now,
        ),
        EditorBlock(
          id: 'b-13',
          type: BlockType.bulletList,
          content: 'Domain: Pure immutable entities, Value Objects, and Repository interfaces',
          createdAt: now,
          updatedAt: now,
        ),
        EditorBlock(
          id: 'b-14',
          type: BlockType.bulletList,
          content: 'Data: Local storage repositories with dirty-queue synchronization engine',
          createdAt: now,
          updatedAt: now,
        ),
        EditorBlock(
          id: 'b-15',
          type: BlockType.divider,
          content: '',
          createdAt: now,
          updatedAt: now,
        ),
        EditorBlock(
          id: 'b-16',
          type: BlockType.heading2,
          content: 'Next Steps',
          createdAt: now,
          updatedAt: now,
        ),
        EditorBlock(
          id: 'b-17',
          type: BlockType.checklist,
          content: 'Implement Notion-style block editor slash command menu',
          isChecked: true,
          createdAt: now,
          updatedAt: now,
        ),
        EditorBlock(
          id: 'b-18',
          type: BlockType.checklist,
          content: 'Connect drag-and-drop block reordering',
          isChecked: true,
          createdAt: now,
          updatedAt: now,
        ),
      ],
      createdAt: now.subtract(const Duration(days: 5)),
      updatedAt: now,
    ),
    NotePage(
      id: 'page-meeting-notes',
      title: 'Weekly Sprint Sync & Notes',
      icon: '📝',
      isFavorite: false,
      projectId: 'proj-med-ai',
      parentPageId: 'page-research-notes', // Nested child page!
      tags: ['Review'],
      blocks: [
        EditorBlock(
          id: 'b-20',
          type: BlockType.heading2,
          content: 'Discussion Summary',
          createdAt: now,
          updatedAt: now,
        ),
        EditorBlock(
          id: 'b-21',
          type: BlockType.numberedList,
          content: 'Elena presented preliminary multimodal metrics.',
          createdAt: now,
          updatedAt: now,
        ),
        EditorBlock(
          id: 'b-22',
          type: BlockType.numberedList,
          content: 'Kibret agreed to lead the final ablation table.',
          createdAt: now,
          updatedAt: now,
        ),
      ],
      createdAt: now.subtract(const Duration(days: 2)),
      updatedAt: now,
    ),
  ];
}
